import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { Flex, Heading, Text } from "@chakra-ui/layout";
import { Button } from "@chakra-ui/button";
import { LargeContainer } from "../../components/container";
import { Hero } from "../../components/hero";
import useSWR from "swr";
import { AlarmSystem } from "@prisma/client";
import { EditAlarmsystemDataForm } from "../../components/edit-alarmsystem-data-form";
import { useRouter } from "next/router";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function Alarmsystem() {
  const router = useRouter();
  const { alarmsystemId } = router.query;

  const { data: session } = useSession();
  const {
    data: alarmsystem,
    error: alarmError,
    isValidating: isValidatingAlarmSystems,
  } = useSWR<AlarmSystem, Error>(`/api/alarmsystems/${alarmsystemId}`, fetcher);

  if (alarmError) return <div>failed to load</div>;
  if (isValidatingAlarmSystems) return <div>loading...</div>;
  console.log(alarmsystem);
  return (
    <>
      <Head>
        <title>Alarmanlage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero src={"/about1600x500.jpg"}>
        {session ? (
          <>
            <Flex width="100%" justifyContent="flex-end">
              <Button
                width="fit-content"
                margin="2rem"
                colorScheme="yellow"
                onClick={() => signOut()}
              >
                Sign out
              </Button>
            </Flex>
            {/* <LargeContainer>
              <Flex
                direction="column"
                width="100%"
                justifyContent="center"
                alignItems="center"
              >
                <Heading as="h1" variant="large">
                  Alarmanlage
                </Heading>
                <Text>Nimm Änderungen an deiner Alarmanlage vor.</Text>
              </Flex>
            </LargeContainer> */}
          </>
        ) : (
          <LargeContainer>
            <Text>Bitte Logge dich ein, um Deine private Seite zu sehen!</Text>
          </LargeContainer>
        )}
        {session ? (
          <></>
        ) : (
          <>
            <LargeContainer>
              <Button
                marginTop="2rem"
                colorScheme="yellow"
                onClick={() => signIn()}
              >
                Sign in
              </Button>
            </LargeContainer>
          </>
        )}
      </Hero>

      {session ? (
        <>
          <LargeContainer>
            <Flex
              direction="column"
              width="100%"
              justifyContent="center"
              alignItems="center"
            >
              <Flex
                direction="column"
                margin="2rem"
                justifyContent="center"
                alignItems="center"
              >
                <Heading as="h2"> Dein Alarmsystem</Heading>

                {alarmsystem ? (
                  <EditAlarmsystemDataForm
                    alarmsystem={alarmsystem}
                  ></EditAlarmsystemDataForm>
                ) : (
                  <Text>Keine Alarmsysteme vorhanden</Text>
                )}
              </Flex>
            </Flex>
          </LargeContainer>
        </>
      ) : (
        <></>
      )}
    </>
  );
}
