import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/client";
import { Flex, Heading, Text } from "@chakra-ui/layout";
import { Button } from "@chakra-ui/button";
import { LargeContainer } from "../components/container";
import { Hero } from "../components/hero";
import { prismaClient } from "../prismaClient";
// import { Alarm, User } from "@prisma/client";
// import { AlarmTable } from "../components/alarm-table";
import { EditForm } from "../components/form";
import { useState } from "react";
import { WelcomeHomeArea } from "../components/welcome-home-area";

export default function Settings() {
  const [session] = useSession();
  return (
    <>
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero src={"/about1600x500.jpg"}>
        {session ? (
          <>
            <Flex width="100%" justifyContent="flex-end">
              <Button
                width="fit-content"
                margin="2rem"
                colorScheme="yellow"
                onClick={() => signOut()}
              >
                Sign out
              </Button>
            </Flex>
            <LargeContainer>
              <Flex
                direction="column"
                width="100%"
                justifyContent="center"
                alignItems="center"
              >
                <Heading as="h1" variant="large">
                  Einstellungen
                </Heading>
                <Text>
                  Nimm Änderungen an deinen persönlichen Daten vor und bearbeite
                  dein Alarmsystem.
                </Text>
              </Flex>
            </LargeContainer>
          </>
        ) : (
          <LargeContainer>
            <Text>Bitte Logge dich ein, um Deine private Seite zu sehen!</Text>
          </LargeContainer>
        )}
        {session ? (
          <></>
        ) : (
          <>
            <LargeContainer>
              <Button
                marginTop="2rem"
                colorScheme="yellow"
                onClick={() => signIn()}
              >
                Sign in
              </Button>
            </LargeContainer>
          </>
        )}
      </Hero>
      <LargeContainer>
        {session ? (
          <>
            <Flex width="100%" direction="column">
              <Heading as="h2"> Deine persönlichen Daten</Heading>
              <EditForm initialUser={session.user}></EditForm>
            </Flex>
          </>
        ) : (
          <></>
        )}
      </LargeContainer>
    </>
  );
}
