import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/client";
import { Flex, Heading, Text } from "@chakra-ui/layout";
import { Button } from "@chakra-ui/button";
import { LargeContainer } from "../components/container";
import { Hero } from "../components/hero";
import { prismaClient } from "../prismaClient";
// import { Alarm, User, SensorStatus } from "@prisma/client";
// import { AlarmTable } from "../components/alarm-table";
import { EditForm } from "../components/form";
import { useState } from "react";
import { WelcomeHomeArea } from "../components/welcome-home-area";

// export async function getServerSideProps() {
//   // const alarms: Alarm[] = await prismaClient.alarm.findMany();
//   // return {
//   //   props: {
//   //     initialAlarms: alarms,
//   //   },
//   // };
// }

export default function Zuhause() {
  const [session] = useSession();
  // const [alarms, setAlarms] = useState<Alarm[]>(initialAlarms);

  // const user = initialUser;
  return (
    <>
      <Head>
        <title>Alarmanlage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero src={"/about1600x500.jpg"}>
        {session ? (
          <>
            <Flex width="100%" justifyContent="flex-end">
              <Button
                width="fit-content"
                margin="2rem"
                colorScheme="yellow"
                onClick={() => signOut()}
              >
                Sign out
              </Button>
            </Flex>
            <LargeContainer>
              <Flex
                direction="column"
                width="100%"
                justifyContent="center"
                alignItems="center"
              >
                <Heading as="h1" variant="large">
                  Willkommen in Deinem sicheren Zuhause!
                </Heading>
                <Text>
                  Überprüfe Dein Alarmsystem, nimm Änderungen vor und sieh Dir
                  Deine Alarmhistorie an.
                </Text>
              </Flex>
            </LargeContainer>
            <LargeContainer>
              <Flex width="100%" justifyContent="center">
                <Flex
                  direction="column"
                  alignItems="center"
                  justifyContent="center"
                  margin="1rem"
                  width="fit-content"
                >
                  <WelcomeHomeArea user={session.user}></WelcomeHomeArea>
                </Flex>
              </Flex>
            </LargeContainer>
          </>
        ) : (
          <LargeContainer>
            <Text>Bitte Logge dich ein, um Deine private Seite zu sehen!</Text>
          </LargeContainer>
        )}
        {session ? (
          <></>
        ) : (
          <>
            <LargeContainer>
              <Button
                marginTop="2rem"
                colorScheme="yellow"
                onClick={() => signIn()}
              >
                Sign in
              </Button>
            </LargeContainer>
          </>
        )}
      </Hero>
      <LargeContainer>
        {session ? (
          <>
            {/* <AlarmTable
              alarms={alarms}
              sensorStatuses={initialSensorStatuses}
            /> */}
          </>
        ) : (
          <></>
        )}
      </LargeContainer>
    </>
  );
}
