import Head from "next/head";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/client";
import { Heading, Text } from "@chakra-ui/layout";
import { Button } from "@chakra-ui/button";
import { LargeContainer } from "../components/container";
import { Hero } from "../components/hero";

export default function Zuhause() {
  const [session, loading] = useSession();

  if (loading) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Alarmanlage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero src={"/about1600x500.jpg"}>
        {session ? (
          <LargeContainer>
            <Heading as="h1" variant="large">
              Willkommen in Deinem sicheren Zuhause!
            </Heading>
            <Text>
              Überprüfe Dein Alarmsystem, nimm Änderungen vor und sieh Dir Deine
              Alarmhistorie an.
            </Text>
          </LargeContainer>
        ) : (
          <LargeContainer>
            <Text>Bitte Logge dich ein, um Deine private Seite zu sehen!</Text>
          </LargeContainer>
        )}
        {session ? (
          <>
            <LargeContainer>
              <Text>
                Du bist eingeloggt als{" "}
                {session.user.name ? session.user.name : session.user.email}
              </Text>
              <Button
                marginTop="2rem"
                colorScheme="yellow"
                onClick={() => signOut()}
              >
                Sign out
              </Button>{" "}
            </LargeContainer>
          </>
        ) : (
          <>
            <LargeContainer>
              <Button
                marginTop="2rem"
                colorScheme="yellow"
                onClick={() => signIn()}
              >
                Sign in
              </Button>
            </LargeContainer>
          </>
        )}
      </Hero>
    </>
  );
}
